version: "3"
services:
  app:
    container_name: pepper-star-wars-api
    build: .
    ports:
    - "3000:3000"
    depends_on:
    - mongo
    environment:
      MONGODB_URI: mongodb://mongo/StarWars
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"
